version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

formats:
    - epub

python:
  version: 3.7
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/readthedocs.txt
